import React from 'react';
import { Card, Alert, BackTop } from 'antd';
import { FormattedHTMLMessage } from 'react-intl';
import I18nProvider from '@/lang';

export default function({ title }) {
  return (
    <I18nProvider scope="components">
      <BackTop />
      <Card title={title}>
        <Alert
          message={<FormattedHTMLMessage id="backToTopTips1" />}
          description={<FormattedHTMLMessage id="backToTopTips2" />}
          type="info"
          showIcon
        />
        <div>
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
        </div>
      </Card>
    </I18nProvider>
  );
}
